### PR TITLE
Keyword search

### PR DESCRIPTION
**Pull request by jarrielcook**
I added a feature that extracts the keywords for each paper from the SQLite database and adds the keywords to the metadata associated with the paper. The search feature will now search the keywords list in addition to the document title and other metadata. I also added "forward" and "reverse" buttons beside the search box to let you quickly jump to the next or previous paper that matches the search term.
Not sure if you're interested in merging these changes, but I find them useful.

Regards,
Jarriel Cook

### CODE REVIEW

**Comment by plandes** [comment]
Hi @jarrielcook 

This looks great, but one question.  Why did `bootstrap-treeview.min.js` change in [this commit](https://github.com/jarrielcook/zotsite/commit/aba4a38c2b35fa403bfc418a1d33fe495518679e)?  Also, the comment doesn't seem to match the change.

**Comment by jarrielcook** [comment]
> Hi @jarrielcook
> 
> This looks great, but one question. Why did `bootstrap-treeview.min.js` change in [this commit](https://github.com/jarrielcook/zotsite/commit/aba4a38c2b35fa403bfc418a1d33fe495518679e)? Also, the comment doesn't seem to match the change.

Ahh. A more accurate comment would be 'Patched bootstrap-treeview.min.js to search "metadata" rather than "text" field.' 

At some point while debugging I thought the findNodes function in bootstrap-treeview-min.js needed to search the "metadata" field rather than the "text" field (char offset 15988).  I thought at one point that change was needed to find the "keywords" I added to the "metadata." 

I just removed that patch in a branch and verified that the search still works. 

In hind sight that would be unmaintainable since bootstrap is a separate library. 

I will update and submit a new pull request if you're still open to accepting.

**Comment by plandes** [comment]
@jarrielcook That makes sense. I am wary of changes to (binary like) files.  The "right" way to deal with these files is to minify from the original. But I opted for fewer moving parts at the time.

Submit a pull request with the reversion and I'll take a look.

Thank you.

**Comment by jarrielcook** [comment]
@plandes After reverting the change to bootstrap-treeview.min.js on a branch and conducting a thorough test, I have come to the unfortunate conclusion that the change was necessary to support the keyword search feature. Without that change, Treeview only searches each Treeview node's "text" element, which contains the document title. I completely agree with you that changing (binary-like) files is not the way to go, so I'm abandoning this pull request. Thanks for being open to collaborating on this.  Best regards.

**Comment by plandes** [comment]
@jarrielcook Can you track down the non-minified version, edit that, then resubmit?

It sounds like a nice feature and would be a shame to abandon it just for this reason.

**Comment by jarrielcook** [comment]
@plandes Sure!  I will do that.

**Pull request closed without merging**
